CREATE DATABASE exempleJDBC1;

USE exempleJDBC1;

CREATE TABLE contact(
id BIGINT NOT NULL AUTO_INCREMENT,
phone VARCHAR(20),
email VARCHAR(50),
PRIMARY KEY(id)
);

CREATE TABLE address(
id BIGINT NOT NULL AUTO_INCREMENT,
uf VARCHAR(2),
city VARCHAR(255),
district VARCHAR(255),
street VARCHAR(255),
number VARCHAR(20),
PRIMARY KEY(id)
);

CREATE TABLE people(
id BIGINT NOT NULL AUTO_INCREMENT,
name VARCHAR(255) NOT NULL,
lastname VARCHAR(255) NOT NULL,
cpf VARCHAR(20),
rg VARCHAR(20),
maritalStatus VARCHAR(30),
gender CHAR(1),
birth DATE,
contact_id BIGINT,
address_id BIGINT NOT NULL,
PRIMARY KEY(id),
FOREIGN KEY(contact_id) REFERENCES contact(id)
ON DELETE RESTRICT
ON UPDATE CASCADE,
FOREIGN KEY(address_id) REFERENCES address(id)
ON DELETE CASCADE
ON UPDATE CASCADE
); 

